# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 16:35
from __future__ import unicode_literals

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("classes", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("has_lab", models.BooleanField(default=False)),
                ("fall", models.BooleanField(default=False)),
                ("winter", models.BooleanField(default=False)),
                ("summer", models.BooleanField(default=False)),
                (
                    "runs",
                    models.CharField(
                        choices=[
                            ("a", "all years"),
                            ("o", "odd years"),
                            ("e", "even years"),
                            ("i", "irregular"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="classes.Course"
                    ),
                ),
            ],
            options={"ordering": ("course",)},
        ),
        migrations.CreateModel(
            name="CourseProgramInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("usual_program_year", models.PositiveSmallIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_planning.CourseInfo",
                    ),
                ),
            ],
            options={"ordering": ("usual_program_year", "course")},
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("verbose_name", models.CharField(max_length=64)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=64,
                        populate_from="verbose_name",
                        unique=True,
                    ),
                ),
                ("ordering", models.PositiveSmallIntegerField(default=100)),
            ],
            options={"ordering": ("ordering", "verbose_name")},
        ),
        migrations.AddField(
            model_name="courseprograminfo",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course_planning.Program",
            ),
        ),
    ]
