# Generated by Django 2.0.1 on 2018-02-01 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("people", "0001_initial"),
        ("course_planning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTeachingPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(9)],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={
                            "active": True,
                            "courseinfo__courseprograminfo__program__scheduled": True,
                            "department__active": True,
                            "department__advertised": True,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.Course",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="TeachingProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "preference_same_day",
                    models.BooleanField(
                        default=False,
                        help_text="Select this if you would prefer to have all of your teaching on the same day",
                    ),
                ),
                (
                    "preference_no_back_to_back",
                    models.BooleanField(
                        default=False,
                        help_text="Select this if you would prefer not to have any back to back teaching",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        limit_choices_to={"active": True, "flags__slug": "intructor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.Person",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="TimeslotTeachingPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(9)],
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        limit_choices_to={"active": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_planning.TeachingProfile",
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        limit_choices_to={"active": True, "scheduled": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.Timeslot",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterModelOptions(
            name="courseinfo",
            options={
                "base_manager_name": "objects",
                "ordering": ("course",),
                "verbose_name": "Course information",
                "verbose_name_plural": "Course information",
            },
        ),
        migrations.AlterModelOptions(
            name="courseprograminfo",
            options={
                "base_manager_name": "objects",
                "ordering": ("usual_program_year", "course"),
                "verbose_name": "Course program information",
                "verbose_name_plural": "Course program information",
            },
        ),
        migrations.AlterModelOptions(
            name="program",
            options={
                "base_manager_name": "objects",
                "ordering": ("ordering", "verbose_name"),
            },
        ),
        migrations.AddField(
            model_name="program",
            name="scheduled",
            field=models.BooleanField(
                default=False,
                help_text="Use courses in this program for scheduling",
                verbose_name="Use for scheduling",
            ),
        ),
        migrations.AlterField(
            model_name="courseinfo",
            name="course",
            field=models.OneToOneField(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.Course",
            ),
        ),
        migrations.AlterField(
            model_name="courseinfo",
            name="runs",
            field=models.CharField(
                choices=[
                    ("a", "all years"),
                    ("o", "odd years"),
                    ("e", "even years"),
                    ("i", "irregular"),
                ],
                default="a",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="courseprograminfo",
            name="course",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="course_planning.CourseInfo",
            ),
        ),
        migrations.AlterField(
            model_name="courseprograminfo",
            name="program",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="course_planning.Program",
            ),
        ),
        migrations.AddField(
            model_name="courseteachingpreference",
            name="profile",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="course_planning.TeachingProfile",
            ),
        ),
    ]
