# Generated by Django 2.0.1 on 2018-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0002_auto_20180201_1022")]

    operations = [
        migrations.AddField(
            model_name="teachingprofile",
            name="agreed_load",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="For the upcoming regular session only"
            ),
        )
    ]
