# Generated by Django 2.0.1 on 2018-02-07 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0006_auto_20180206_0816")]

    operations = [
        migrations.AlterModelOptions(
            name="semesterteachingpreference",
            options={"ordering": ("profile", "-semester")},
        ),
        migrations.AddField(
            model_name="teachingprofile",
            name="last_reviewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semesterteachingpreference",
            name="preferred_load",
            field=models.FloatField(
                default=1.5,
                validators=[
                    django.core.validators.MaxValueValidator(9),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
