# Generated by Django 2.0.1 on 2018-02-07 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0007_auto_20180207_0953")]

    operations = [
        migrations.AlterField(
            model_name="teachingprofile",
            name="person",
            field=models.OneToOneField(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
            ),
        )
    ]
