# Generated by Django 2.0.1 on 2018-02-12 21:27

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0020_auto_20180201_1022"),
        ("course_planning", "0008_auto_20180207_1016"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftScheduleSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "verbose_name",
                    models.CharField(
                        help_text='e.g., "Regular Session 2018-2019"', max_length=128
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        max_length=128,
                        populate_from="verbose_name",
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "even_or_odd_run",
                    models.CharField(
                        choices=[("o", "odd year"), ("e", "even year")], max_length=2
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DraftSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "verbose_name",
                    models.CharField(help_text='e.g., "A01"', max_length=16),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("1", "Winter"), ("3", "Fall")], max_length=2
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        limit_choices_to={
                            "active": True,
                            "courseinfo__courseprograminfo__program__active": True,
                            "courseinfo__courseprograminfo__program__scheduled": True,
                            "department__active": True,
                            "department__advertised": True,
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.Course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_planning.TeachingProfile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_planning.DraftScheduleSession",
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"active": True, "scheduled": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.Timeslot",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
