# Generated by Django 2.0.1 on 2018-02-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0020_auto_20180201_1022"),
        ("course_planning", "0009_draftschedulesession_draftsection"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="draftsection",
            unique_together={("course", "verbose_name", "session", "semester")},
        )
    ]
