# Generated by Django 2.0.1 on 2018-02-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0010_auto_20180212_1529")]

    operations = [
        migrations.RenameField(
            model_name="draftschedulesession",
            old_name="even_or_odd_run",
            new_name="even_or_odd_session",
        )
    ]
