# Generated by Django 2.0.1 on 2018-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0011_auto_20180212_1546")]

    operations = [
        migrations.RemoveField(
            model_name="draftschedulesession", name="even_or_odd_session"
        )
    ]
