# Generated by Django 2.0.1 on 2018-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_planning", "0012_remove_draftschedulesession_even_or_odd_session")
    ]

    operations = [
        migrations.AddField(
            model_name="draftschedulesession",
            name="initialized",
            field=models.BooleanField(default=False),
        )
    ]
