# Generated by Django 2.0.1 on 2018-02-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0013_draftschedulesession_initialized")]

    operations = [
        migrations.AlterModelOptions(
            name="courseteachingpreference", options={"ordering": ("profile", "course")}
        ),
        migrations.AlterModelOptions(
            name="timeslotteachingpreference",
            options={"ordering": ("profile", "timeslot")},
        ),
        migrations.AlterField(
            model_name="draftsection",
            name="course",
            field=models.ForeignKey(
                limit_choices_to={
                    "active": True,
                    "department__active": True,
                    "department__advertised": True,
                },
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.Course",
            ),
        ),
    ]
