# Generated by Django 2.0.2 on 2018-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0014_auto_20180216_1121")]

    operations = [
        migrations.AlterModelOptions(
            name="teachingsurveyanswer", options={"ordering": ("profile", "question")}
        ),
        migrations.AlterField(
            model_name="draftsection",
            name="verbose_name",
            field=models.CharField(
                help_text='e.g., "A01"', max_length=16, verbose_name="section"
            ),
        ),
    ]
