# Generated by Django 2.0.4 on 2018-04-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0015_auto_20180226_0953")]

    operations = [
        migrations.AlterModelOptions(
            name="draftsection",
            options={"ordering": ("session", "-semester", "course", "verbose_name")},
        ),
        migrations.AlterUniqueTogether(
            name="courseprograminfo", unique_together={("course", "program")}
        ),
    ]
