# Generated by Django 2.0.4 on 2018-04-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0015_auto_20180226_0953")]

    operations = [
        migrations.AlterModelOptions(
            name="teachingprofile", options={"ordering": ("person",)}
        )
    ]
