# Generated by Django 2.0.4 on 2018-04-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_planning", "0016_auto_20180411_1014"),
        ("course_planning", "0016_auto_20180418_0841"),
    ]

    operations = []
