# Generated by Django 2.1.4 on 2018-12-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0018_courseprograminfo_contraint")]

    operations = [
        migrations.AddField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, help_text="About the program."),
        )
    ]
