# Generated by Django 2.1.4 on 2018-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0019_program_description")]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(
                blank=True,
                help_text='About the program. This will be processed as\n<a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_blank">\nReStructuredText</a>.',
            ),
        )
    ]
