# Generated by Django 2.2 on 2019-04-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0020_auto_20181219_1004")]

    operations = [
        migrations.AddField(
            model_name="courseprograminfo",
            name="usual_year",
            field=models.CharField(
                choices=[
                    ("0", "Not applicable"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("3/4", "3/4"),
                    ("4", "4"),
                    ("msc", "1"),
                    ("phd", "1"),
                ],
                default="0",
                max_length=8,
            ),
        )
    ]
