# Generated by Django 2.2 on 2019-04-30 13:47

from django.db import migrations


def forward_data(apps, schema_editor):
    """
    Forward data migration:
        convert ``usual_program_year: int`` to ``usual_year: str``
    """
    model = apps.get_model("course_planning", "CourseProgramInfo")
    qs = model.objects.all()
    for o in qs.iterator():
        o.usual_year = str(o.usual_program_year)
        o.save()


def backward_data(apps, schema_editor):
    """
    Backward data migration:
        convert ``usual_year: str`` to ``usual_program_year: int``.
        This is a lossy conversion.
    """
    model = apps.get_model("course_planning", "CourseProgramInfo")
    qs = model.objects.all()
    for o in qs.iterator():
        try:
            o.usual_program_year = int(o.usual_year)
        except ValueError:
            o.usual_program_year = 0
        o.save()


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0021_courseprograminfo_usual_year")]

    operations = [migrations.RunPython(forward_data, backward_data)]
