# Generated by Django 2.2.1 on 2019-05-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("course_planning", "0023_auto_20190430_0858")]

    operations = [
        migrations.RenameField(
            model_name="courseprograminfo", old_name="contraint", new_name="constraint"
        )
    ]
